INSERT INTO PERSONA (PERSONA_ID, NOMBRE, APELLIDOS, CORREO, TELEFONO, SOCIO) VALUES (1,'Roberto','Marin','roberto@correo','723456789', 'Si');
INSERT INTO PERSONA (PERSONA_ID, NOMBRE, APELLIDOS, CORREO, TELEFONO, SOCIO) VALUES (2, 'Isabel', 'Gil', 'isabel@correo', '623654947', 'No');
INSERT INTO PERSONA (PERSONA_ID, NOMBRE, APELLIDOS, CORREO, TELEFONO, SOCIO) VALUES (3,'Lucas','Vidal','lucas@correo','623456789', 'Si');
INSERT INTO PERSONA (PERSONA_ID, NOMBRE, APELLIDOS, CORREO, TELEFONO, SOCIO) VALUES (4, 'Andrea', 'Dorantes', 'andrea@correo', '647232369', 'No');

INSERT INTO BARCO(BARCO_ID, MATRICULA, NOMBRE, NUM_AMARRE, CUOTA, SOCIO_ID) VALUES (1,'78562-Q', 'Niña', 1, 250,1);
INSERT INTO BARCO(BARCO_ID, MATRICULA, NOMBRE, NUM_AMARRE, CUOTA, SOCIO_ID) VALUES (2,'45823-E', 'Pinta', 3, 100,3);
INSERT INTO BARCO(BARCO_ID, MATRICULA, NOMBRE, NUM_AMARRE, CUOTA, SOCIO_ID) VALUES (3,'65454-K', 'Santa María', 3, 425,3);
INSERT INTO BARCO(BARCO_ID, MATRICULA, NOMBRE, NUM_AMARRE, CUOTA, SOCIO_ID) VALUES (4,'99999-Z', 'Titanic', 2, 600,1);

INSERT INTO SALIDA(SALIDA_ID, FECHA, HORA, DESTINO, BARCO_ID, PERSONA_ID) VALUES (1,'01/12/2023', '14:30:15','Alejandria', 1,2);
INSERT INTO SALIDA(SALIDA_ID, FECHA, HORA, DESTINO, BARCO_ID, PERSONA_ID) VALUES (2,'20/06/2022', '20:00:45','Napoles', 2,2);
INSERT INTO SALIDA(SALIDA_ID, FECHA, HORA, DESTINO, BARCO_ID, PERSONA_ID) VALUES (3,'10/03/2022', '09:15:00','Helsinki', 3,3);
INSERT INTO SALIDA(SALIDA_ID, FECHA, HORA, DESTINO, BARCO_ID, PERSONA_ID) VALUES (4,'12/10/2021', '11:18:24','Nueva York', 4,4);